/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * GimmeVibe API
 * For using awesome someapp
 * OpenAPI spec version: v0.0.1
 */

export interface LikePostRequest {
    postUserId: string;
    postId: string;
}
