/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * GimmeVibe API
 * For using awesome someapp
 * OpenAPI spec version: v0.0.1
 */
import type { HttpStatus } from './httpStatus';

export interface PingResponse {
    httpStatus: HttpStatus;
    date: string;
}
