/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * GimmeVibe API
 * For using awesome someapp
 * OpenAPI spec version: v0.0.1
 */

export interface RelationshipDTO {
    uuid: string;
    createdDate?: string;
    userId: string;
    relationshipWithId: string;
    uniqueId: string;
    status: number;
}
