/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * GimmeVibe API
 * For using awesome someapp
 * OpenAPI spec version: v0.0.1
 */
import type { PostDTO } from './postDTO';
import type { PostLikeDTO } from './postLikeDTO';
import type { RelationshipDTO } from './relationshipDTO';

export interface UserDTO {
    uuid: string;
    createdDate?: string;
    username: string;
    admin: boolean;
    posts?: PostDTO[];
    likedPostsIds?: PostLikeDTO[];
    relationships?: RelationshipDTO[];
    likedPosts?: PostLikeDTO[];
}
