name: Frontend CI workflow

on: [push]

jobs:
    deploy:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js v18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Run clean install
              run: npm ci
            #- name: Run linter
            #  run: npm run lint
            - name: Run tests
              run: npm run test
